### ISSUE TITLE
Couple of issues

### ISSUE THREAD

**Issue by german-one** [bitcrazed/Paws#2]
Nice little exercise but it has various issues.

<br>

----
https://github.com/bitcrazed/Paws/blob/c9877d23ca55d0db5ca05818a9392e2687d75f4a/Paws/Paws.cpp#L13
Unused code.

----
https://github.com/bitcrazed/Paws/blob/c9877d23ca55d0db5ca05818a9392e2687d75f4a/Paws/Paws.cpp#L16
Unused parameter.

----
https://github.com/bitcrazed/Paws/blob/c9877d23ca55d0db5ca05818a9392e2687d75f4a/Paws/Paws.cpp#L21
No need for global variables. Consider to put them into a class and pass a constant reference to the functions where coloring is used.

----
https://github.com/bitcrazed/Paws/blob/c9877d23ca55d0db5ca05818a9392e2687d75f4a/Paws/Paws.cpp#L47-L53
**Bug**
You can't compare the length of `argv[0]` with the length of the first token in the command line. Surrounding quotes are removed in the argv elements. So, you will have different lengths if you call the program quoted or unquoted. Think about rolling your own parser to skip the first token. It's pretty straightforward. (See the next sub-issue.)

----
https://github.com/bitcrazed/Paws/blob/c9877d23ca55d0db5ca05818a9392e2687d75f4a/Paws/Paws.cpp#L61
**Bug**
This causes undefined behavior. `CreateProcessW` will alter the string as the documentation states.
As suggested before, parse the command line in a custom function and find the pointer to the second token. Use the C-string rather than an STL string since the string returned by `GetCommandLineW` is mutable as `CreateProcessW` requires it. E.g.:
```
LPWSTR GetCmdLnSkipFirstToken()
{
    static LPWSTR cmdLn{};
    bool isInQuotes{};
    bool isInToken{};
    DWORD tokensCnt{};

    if (cmdLn == nullptr)
        cmdLn = GetCommandLineW();

    for (LPWCH cursor{ cmdLn }; *cursor != L'\0'; ++cursor)
    {
        switch (*cursor)
        {
        case L' ': case L'\t': // Token separators, unless in a quoted substring
            if (isInQuotes == false)
                isInToken = false;
            break;

        case L'\"':
            isInQuotes = !isInQuotes;
        default: // This includes quotation marks
            if (isInToken == false)
            {
                ++tokensCnt;
                if (tokensCnt > 1) // That is, the cursor points to the beginning of the second token
                    return cursor;

                isInToken = true;
            }
            break;
        }
    }

    return nullptr;
}
```
Further advantages:
* you don't need to copy the C-strings into STL string classes
* you can use `main()` rather than `wmain()` to eliminate compiler dependencies because you don't need `argc` and `argv` anymore. Just call your `DisplayUsage` if nullptr was returned by the above function

----
https://github.com/bitcrazed/Paws/blob/c9877d23ca55d0db5ca05818a9392e2687d75f4a/Paws/Paws.cpp#L72-L73
Thread handle and process handle have to be closed according to the specification. This is missing after `WaitForSingleObject` here.

----
https://github.com/bitcrazed/Paws/blob/c9877d23ca55d0db5ca05818a9392e2687d75f4a/Paws/Paws.cpp#L76
It's an error message. Consider to write to the `wcerr` stream.

----
https://github.com/bitcrazed/Paws/blob/c9877d23ca55d0db5ca05818a9392e2687d75f4a/Paws/Paws.cpp#L82
The main routine implicitely returns 0, always. What about catching the exit code of the executed command for a proper return value. Or perhaps use the last-error code if `CreateProcessW` failed.

----
https://github.com/bitcrazed/Paws/blob/c9877d23ca55d0db5ca05818a9392e2687d75f4a/Paws/Paws.cpp#L89
This polling loop causes a noticeable increase of CPU usage. Consider to replace this line with
`static_cast<void>(_getwch());`

----
https://github.com/bitcrazed/Paws/blob/c9877d23ca55d0db5ca05818a9392e2687d75f4a/Paws/Paws.cpp#L115
**Bug**
This doesn't work because you effectively pass a null pointer. The parameter type is quite misleading in case you specified `FORMAT_MESSAGE_FROM_SYSTEM`. Nevertheless you have to pass the address of the pointer variable here.
`reinterpret_cast<LPWSTR>(&lpMsgBuf),`

----
https://github.com/bitcrazed/Paws/blob/c9877d23ca55d0db5ca05818a9392e2687d75f4a/Paws/Paws.cpp#L118
**Bug**
Since you don't check if `FormatMessageW` was successful you may cause undefined behavior here if you pass a null pointer to the constructor of the string.

----
https://github.com/bitcrazed/Paws/blob/c9877d23ca55d0db5ca05818a9392e2687d75f4a/Paws/Paws.cpp#L125-L135
This is cumbersome. Proposal:
```
bool EnableVTProcessing()
{
    DWORD consoleMode{};
    HANDLE hConsole = { GetStdHandle(STD_OUTPUT_HANDLE) };
    return (GetConsoleMode(hConsole, &consoleMode) != FALSE &&
        SetConsoleMode(hConsole, consoleMode | ENABLE_VIRTUAL_TERMINAL_PROCESSING) != FALSE);
}
```

----
A couple of ANSI string literals are used for the output to the wcout stream.

----
<br>
<br>

Best regards
Steffen

**Comment by bitcrazed** [comment]
Many thanks for your detailed review. Will address your feedback shortly :)
